### ISSUE TITLE
Correlation data region

### ISSUE THREAD

**Issue by Gregor0815** [EuropeanForestInstitute/tradeflows#1]
Could you please provide me the file with correlation of regions and comtrade country codes? I am not able to find those information.

thanks a lot!

**Comment by paul4forest** [comment]
Regions used in the package are those defined by ITTO in the file [data-raw/ITTO_reporters.csv](https://github.com/EuropeanForestInstitute/tradeflows/blob/master/data-raw/ITTO_reporters.csv). This .csv file was not tracked by git, in commit 7d10b502 I have added ceveral csv files including this one. 

Once the package is loaded the region to country mapping will be available to you in a data frame called classification
```r
library(tradeflows)
View(reportercomtrade)
```

For more on how this `reportercomtrade` data frame is created by mixing country codes from Comtrade, ITTO and FAOSTAT, look at [data-raw/reporter_names.R](https://github.com/EuropeanForestInstitute/tradeflows/blob/master/data-raw/reporter_names.R).

**Comment by Gregor0815** [comment]
Only for information: the Comtrade Country Code 652 (Saint Barthélemy) is missing in [https://github.com/EuropeanForestInstitute/tradeflows/blob/master/data-raw/ITTO_reporters.csv](url)
